export const AUTH_CHECKING = 'AUTH_CHECKING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const REPO_PROGRESS = 'REPO_PROGRESS';
export const CREATE_REPO_SUCCESS = 'CREATE_REPO_SUCCESS';
export const CREATE_REPO_FAIL = 'CREATE_REPO_FAIL';
export const GET_REPO_SUCCESS = 'REPO_SUCCESS';
export const GET_REPO_FAIL = 'REPO_FAIL';
export const HAS_REPOS = 'HAS_REPOS';
export const NO_REPOS = 'NO_REPOS';

export const COMMITS_PROGRESS = 'GET_COMMITS_PROGRESS';
export const GET_COMMITS_SUCCESS = 'GET_COMMITS_SUCCESS';
export const GET_COMMITS_FAIL = 'GET_COMMITS_FAIL';
