# Generated by Django 2.2.12 on 2020-05-23 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='github_hook_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'user')},
        ),
    ]
